OBJS = 07_texture_loading_and_rendering.cpp

CC = g++

COMPILE_FLAGS = -w
LINK_FLAGS = -lSDL2 -lSDL2_image
OBJ_NAME = 07_texture_load_and_render

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

