OBJS = 36_multiple_windows.cpp

CC = g++

COMPILE_FLAGS = -w -std=c++11
LINK_FLAGS = -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
OBJ_NAME = 36_multiple_windows

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

