OBJS = 32_text_input_and_clipboard_handling.cpp

CC = g++

COMPILE_FLAGS = -w -std=c++11
LINK_FLAGS = -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
OBJ_NAME = 32_text_input_and_clipboard_handling

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

