OBJS = 02_getting_an_image_on_the_screen.cpp

CC = g++

COMPILE_FLAGS = -w
LINK_FLAGS = -lSDL2
OBJ_NAME = 02_image_on_screen

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

