OBJS = 12_color_modulation.cpp

CC = g++

COMPILE_FLAGS = -w
LINK_FLAGS = -lSDL2 -lSDL2_image
OBJ_NAME = 12_color_modulation

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

