OBJS = 11_clip_rendering_and_sprite_sheets.cpp

CC = g++

COMPILE_FLAGS = -w
LINK_FLAGS = -lSDL2 -lSDL2_image
OBJ_NAME = 11_clip_render

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

