OBJS = 50_SDL_and_opengl_2.cpp

CC = g++

COMPILE_FLAGS = -w
LINK_FLAGS = -lSDL2 -lSDL2_image -lSDL2_ttf -lGL -lGLU
OBJ_NAME = 50_SDL_and_opengl_2

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

