OBJS = 33_file_reading_and_writing.cpp

CC = g++

COMPILE_FLAGS = -w -std=c++11
LINK_FLAGS = -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
OBJ_NAME = 33_file_read_and_write

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

