OBJS = 34_audio_recording.cpp

CC = g++

COMPILE_FLAGS = -w -std=c++11
LINK_FLAGS = -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
OBJ_NAME = 34_audio_record

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

