OBJS = 05_optimized_surface_loading_and_soft_stretching.cpp

CC = g++

COMPILE_FLAGS = -w
LINK_FLAGS = -lSDL2
OBJ_NAME = 05_opt_surface_and_stretch

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

