OBJS = 23_advanced_timers.cpp

CC = g++

COMPILE_FLAGS = -w
LINK_FLAGS = -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
OBJ_NAME = 23_advanced_timers

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILE_FLAGS) $(LINK_FLAGS) -o $(OBJ_NAME)

